POST https://phonebook-api-three.vercel.app/api/persons
Content-Type: application/json

{
    "name": "lo",
    "number": "3456217890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "1234567890"
}


###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "arto hmellas",
    "number": "1234432156"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "David"
}